### ISSUE TITLE
Use new webtrees Validator

### ISSUE THREAD

**Issue by hartenthaler** [huhwt/huhwt-cce#4]
All 
`$xref = $request->getQueryParams()['xref'] ?? '';`
should be replaced by
 `$xref = Validator::attributes($request)->isXref()->string('xref');`

**Comment by huhwt** [comment]
Nope, it doesn't work like that, it's a parameter and not an attribute ... but I found that with the validator also parameters can be drawn - is changed accordingly, see next release.
By the way, in the original ClippingsCartModule the parameters are also still explicitly queried via getQueryParams - probably because the query via the Validator requires the parameter to be mandatory, so you can't set it alternatively depending on the context.
